language: c
os: linux
dist: bionic
compiler:
  - gcc
  - clang
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x
script: ./runtests.sh

jobs:
  include:
    - os: osx
      compiler: clang
      env:
        - NISTFLAGS="-I/usr/local/Cellar/openssl@1.1/1.1.1d/include/"
        - LDFLAGS="-L/usr/local/Cellar/openssl@1.1/1.1.1d/lib/"

    - stage: coverage
      os: linux
      compiler: gcc
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y lcov
        - gem install coveralls-lcov
      script: ./runlcov.sh
      after_success:
        - coveralls-lcov ref/kyber.lcov
